[Interface]
PrivateKey = 2IKMMAekDKPYInN4B4q387NGDHjhVLCq/MY7+HyOq00=
Address = 10.13.37.2/32

[Peer]
PublicKey = mVBIBx+tH30+MV54WgdR+SIfUmKalWq+Q8AJ5wjyZlQ=
Endpoint = <HOST>:<PORT>
AllowedIPs = 10.13.37.1/32
PersistentKeepalive = 25
