name: Issue comment handler

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  process_comment:
    runs-on: ubuntu-slim
    
    steps:
      - name: Extract command from comment
        id: extract
        env:
          FLAG: ${{ secrets.PLFANZEN_FLAG }}
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "comment=$COMMENT_BODY" >> $GITHUB_OUTPUT
